### ISSUE TITLE
[META] Create a RQT Plugin with visualization tools

### ISSUE THREAD

**Issue by Voldivh** [ToyotaResearchInstitute/gauges2#1]
### Goal

Provide a package gives the end user a primitive type visualization of several sensors such as: Brake pedal position, Throttle position, Steering wheel angle, Speedometer, etc. This package end user is directed for operators that need a visual interface (Dashboard) to check the values of several variables related to the work being done.

### Steps

Infra:
 - [x] Create base package.  #2 
 - [x] Setup CI. 
 - [x] Add LICENSE.

Package:
 - [x] Create a base RQT plugin package #2 
 - [x] Provide the visualization features expected (mentioned on the Goal section ) #4 #7 #10 
 - [x] Provide a better border visibility for plugins for resizing.
